input:
  label: entries
  http_server:
    path: /api/v2/entries
    allowed_verbs:
      - GET
    timeout: 5m
    sync_response:
      headers:
        Content-Type: application/json
      status: '${! meta("response_status").or("200") }'
pipeline:
  processors:
    - label: split_ids
      bloblang: |
        root = this
    - javascript:
        code: |
          function sleep(milliseconds) {
            const date = Date.now();
            let currentDate = null;
            do {
              currentDate = Date.now();
            } while (currentDate - date < milliseconds);
          }

          (() => {
            let thing = benthos.v0_msg_as_structured();
            console.log("Hello");
            sleep(6000000);
            console.log("World!");
            benthos.v0_msg_set_structured(thing);
          })();
output:
  label: error_handling
  sync_response: {}
  processors:
    - bloblang: |
        root = if meta().exists("error") { {"error": meta("error")} }
